### ISSUE TITLE
Lightbox modal is not full screen

### ISSUE THREAD

**Issue by gevera** [Hejtmus/svelte-lightbox#11]
Would love to use Lightbox, unfortunately, when I wrap my image in <Lightbox> and trigger the modal, it only takes the size of the parent instead of the whole screen

here is a screenshot

[https://imgur.com/gallery/rwTUmzn](https://imgur.com/gallery/rwTUmzn)

I hope it makes sense

**Comment by Hejtmus** [comment]
Hello,

thank you for reporting this bug and providing screenshot. Today I have some time, so I can try to fix it (and one more visual bug).

Best regards.

**Comment by Hejtmus** [comment]
I tried to replicate your situation. Do you use bootstrap @gevera?

**Comment by gevera** [comment]
> I tried to replicate your situation. Do you use bootstrap @gevera?

No. I do use Tailwind CSS

**Comment by Hejtmus** [comment]
Well, as far as I can see, this bug is related to positioning. It takes size of the whole screen, but for some reason CSS ignores z-index of Lightbox modal (even when I used !important), so if you use CSS frameworks like Bootstrap or Tailwind CSS, components like navbar are displayed above lightbox, even if Lightboxe's z-index is greater. I am still analyzing this issue. Sorry for my bad CSS skills.

**Comment by Hejtmus** [comment]
Hi @gevera,
sorry for huge delay, but I was quite busy, this unwanted character you described here should be gone in version 0.5.0.
If you still use this lib, would be good to know if 0.5.0 did the trick.
I will understand if you won't respond, it has been long wait.
